// Algebra 2 lesson data — 10 lessons covering quadratics.
// Each lesson has learning targets, a teacher plan, and 2–3 activities.
// Activities reference overlay keys used by the chart edu-plugin.

const LESSONS = [
  {
    id: 1,
    title: 'Quadratic Forms',
    targets: [
      'Write and graph quadratic functions in vertex, intercept, and general forms.',
      'Find the vertex and axis of symmetry from the equation of a quadratic.',
      'Identify the x-intercepts of a quadratic written in intercept form.',
      'Rewrite an equation from vertex or intercept form to general form.',
    ],
    plan: {
      overview: 'Students explore how the same parabola can be written in three equivalent forms. The projectile path is a perfect parabola — use the simulator to connect physics to algebra in real time.',
      warmup: 'Launch the minion at 45° with medium speed. Ask: "What shape is this path?" Then: "Can you write an equation for it?" Accept whatever forms students suggest.',
      teacherNotes: [
        'Show all three forms updating live as you change angle and speed. Emphasize: same parabola, three different representations — each reveals something different.',
        'General form y = ax² + bx: note c = 0 because the minion launches from ground level.',
        'Vertex form y = a(x − h)² + k reveals the peak (h, k) directly — the highest point of the flight.',
        'Intercept/factored form y = a(x)(x − R) reveals where the minion launches (x = 0) and lands (x = R).',
        'Toggle each chart overlay on and off to make each form\'s meaning concrete.',
      ],
      discussion: [
        'Why is c = 0 in our general form? (The minion starts at ground level, so y = 0 when x = 0.)',
        'What does the vertex represent physically? (The highest point of the flight — peak height and distance.)',
        'One x-intercept is always at x = 0. Why? (That is the launch point.)',
        'What changes when you increase the launch speed? The angle?',
      ],
      homework: 'Set angle = 30°, speed = 40 m/s, planet = Earth. Write the trajectory equation in all three forms. Calculate the vertex and axis of symmetry. Where does the minion land?',
    },
    activities: [
      {
        id: 'l1-demo',
        title: 'Forms Explorer',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Launch and watch all three equation forms update simultaneously. Point out each form\'s key features using the chart overlays.',
        prompts: [
          'Launch the minion. Watch all three forms in the Equations panel update in real time.',
          'General form: a and b are the raw coefficients. c = 0 because we launch from the ground.',
          'Vertex form: h and k are the coordinates of the highest point. Toggle the vertex overlay!',
          'Intercept form: factors show the two x-intercepts — launch (x = 0) and landing (x = R).',
          'Try different angles. Does the vertex change? Does the shape of the parabola change?',
        ],
        overlays: { vertex: true, axisSym: true, intercepts: true },
        equationForms: ['general', 'vertex', 'factored'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
      {
        id: 'l1-explore',
        title: 'Student Explorer',
        badge: null,
        type: 'student',
        desc: 'Before launching, use the pre-flight equation to predict the vertex and landing point algebraically.',
        prompts: [
          'Look at the general form y = ax² + bx shown. Write down the values of a and b.',
          'Calculate the vertex: h = −b/(2a) is the axis of symmetry; k = −b²/(4a) is the max height.',
          'Write the vertex form: y = a(x − h)² + k using your calculated h and k.',
          'From intercept form y = a·x·(x − R), solve for R. What is the landing distance?',
          'Set the basket to your predicted R value, then launch and check!',
        ],
        overlays: { vertex: false, axisSym: false, intercepts: false },
        equationForms: ['general', 'vertex', 'factored'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
      {
        id: 'l1-hw',
        title: 'Homework Challenge',
        badge: 'HW',
        type: 'homework',
        desc: 'Set the specified parameters, write all three equation forms by hand, then verify with the simulation.',
        prompts: [
          'Set angle = 30° and speed = 40 m/s on Earth. Read a and b from the general form.',
          'Calculate h = −b/(2a). This is the x-coordinate of the vertex (axis of symmetry).',
          'Calculate k = −b²/(4a). This is the maximum height (y-coordinate of vertex).',
          'Write vertex form: y = a(x − h)² + k.',
          'Write intercept form: y = a·x·(x − R) where R = −b/a. Set the basket to R and launch!',
        ],
        overlays: { vertex: false, axisSym: false, intercepts: false },
        equationForms: ['general', 'vertex', 'factored'],
        defaultAngle: 30,
        defaultSpeed: 40,
        defaultPlanet: 'Earth',
        showTargetHeight: false,
        showDiscriminant: false,
      },
    ],
  },

  {
    id: 2,
    title: 'Writing Equations',
    targets: [
      'Write an equation for a quadratic from a graph, table, or description.',
      'Use the symmetry of a quadratic to find values of the function.',
    ],
    plan: {
      overview: 'Students reverse-engineer the trajectory. Given visual or tabular information, they write the equation. Symmetry about the axis is the key tool for finding unknown values without solving the full equation.',
      warmup: 'Show a completed trajectory in the chart (overlays on). Ask: "What information from this graph would let you write the equation?" Accept answers, then discuss which are sufficient.',
      teacherNotes: [
        'Reading from the graph: launch is (0, 0); vertex is (h, k); landing is (R, 0). Two x-intercepts + vertex = enough.',
        'Symmetry key: the axis of symmetry is exactly halfway between the two x-intercepts: h = R/2.',
        'If f(x₁) = y₀ and the axis is at x = h, then f(2h − x₁) = y₀ by symmetry.',
        'In-class activity: give students specific (x, y) pairs and the axis, ask them to find the symmetric point.',
        'From graph: students can read vertex and one other point, then substitute into vertex form to find a.',
      ],
      discussion: [
        'Given only landing distance R and max height k, can you write the equation? What else is needed? (The value of a.)',
        'If you know f(15) = 8 and the axis is at x = 35, what is f(55)? How do you know?',
        'What is the minimum information needed to uniquely determine a quadratic?',
      ],
      homework: 'Launch with any settings. Record 4 (x, y) data points from the chart. Using only two of those points plus the axis of symmetry, write the equation. Verify with the remaining two points.',
    },
    activities: [
      {
        id: 'l2-graph',
        title: 'From Graph',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Launch and let the minion land. Then work backward from the graph to write the equation.',
        prompts: [
          'Launch the minion and let it land. The full trajectory is now visible.',
          'Read key coordinates: launch (0, 0), vertex (h, k) from the chart, landing (R, 0).',
          'Since x-intercepts are 0 and R: write y = a·x·(x − R). Use vertex to find a.',
          'At the vertex x = h = R/2: k = a·(R/2)·(R/2 − R) = a·(R/2)·(−R/2). Solve for a.',
          'Write the equation in all three forms. Check against the Equations panel.',
        ],
        overlays: { vertex: true, axisSym: true, intercepts: true },
        equationForms: ['general', 'vertex', 'factored'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
      {
        id: 'l2-symmetry',
        title: 'Symmetry Explorer',
        badge: null,
        type: 'student',
        desc: 'Use the axis of symmetry to find y-values at symmetric x-positions — without solving the equation.',
        prompts: [
          'The parabola is a perfect mirror image on each side of the axis of symmetry (x = h).',
          'Read the axis of symmetry value from the Equations panel (it is h in the vertex form).',
          'If the minion is at height y₀ when x = x₁, find the symmetric x: x_sym = 2h − x₁.',
          'Example: axis at x = 35. At x = 10, height = 8 m. What x on the descent also has height 8 m?',
          'Answer: 2(35) − 10 = 60 m. Launch and watch the trajectory to verify!',
        ],
        overlays: { vertex: true, axisSym: true },
        equationForms: ['general', 'vertex'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
    ],
  },

  {
    id: 3,
    title: 'Factoring (a = 1)',
    targets: [
      'Multiply polynomial factors using distribution or rectangle diagrams.',
      'Factor quadratic equations in the form ax² + bx + c when a = 1.',
    ],
    plan: {
      overview: 'Students connect the factored form to x-intercepts and practice expanding and reversing polynomial multiplication. One root is always x = 0 for our trajectory — making the factoring concrete and verifiable.',
      warmup: 'Show the intercept form y = a·x·(x − R). Ask: "Can you expand this to get the general form?" Have students do it algebraically, then verify with the Equations panel.',
      teacherNotes: [
        'Expand: a·x·(x − R) = ax² − aRx. Compare with general form: b = −aR, so R = −b/a.',
        'Reverse: given y = ax² + bx, factor out x: y = x(ax + b). Set ax + b = 0 → x = −b/a = R.',
        'Rectangle diagram: rows and columns for x and (x − R). Area = x·(x − R) = x² − Rx.',
        'For unit a: factor x² + bx = x(x + b). The two roots are x = 0 and x = −b.',
        'Our simulation always has c = 0 (launch from ground), so one factor is always x.',
      ],
      discussion: [
        'Why can we always factor out x? (Because x = 0 is always a solution — the launch point.)',
        'Given b = −0.84 and a = −0.012, find R algebraically. Then verify with the simulator.',
        'When is "factor out x" NOT applicable? (When c ≠ 0, i.e., one root isn\'t zero.)',
      ],
      homework: 'For the current simulation, write the general form and factor it completely. List both x-intercepts. Change the planet and repeat — notice how a changes but R = −b/a still holds.',
    },
    activities: [
      {
        id: 'l3-expand',
        title: 'Expand & Factor',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Show the algebraic connection between intercept form (x-intercepts) and general form (expansion).',
        prompts: [
          'Intercept form: y = a·x·(x − R). R is the landing distance.',
          'Expand by distributing: a·x·(x − R) = ax² − aRx. So b = −aR.',
          'Reverse: given y = ax² + bx, factor out x: y = x(ax + b).',
          'Apply ZPP (preview for Lesson 5): x = 0 or ax + b = 0 → x = −b/a = R.',
          'Change angle/speed. Does R = −b/a always give the landing distance?',
        ],
        overlays: { intercepts: true },
        equationForms: ['general', 'factored'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
      {
        id: 'l3-challenge',
        title: 'Factor Challenge',
        badge: null,
        type: 'student',
        desc: 'Factor the general form equation to predict the landing distance, then verify by launching.',
        prompts: [
          'Read a and b from the general form shown in the Equations panel.',
          'Factor: y = ax² + bx = x(ax + b).',
          'Find the non-zero root: set ax + b = 0, so x = −b/a. This is where the minion lands.',
          'Record your predicted landing distance: x = ___ m.',
          'Set the basket to that distance, then launch to check!',
        ],
        overlays: { intercepts: false },
        equationForms: ['general', 'factored'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
    ],
  },

  {
    id: 4,
    title: 'Factoring (a > 1)',
    targets: [
      'Factor quadratic equations in the form ax² + bx + c when a > 1.',
    ],
    plan: {
      overview: 'Extend factoring to non-unit leading coefficients. Different planets produce different values of a in the simulation, giving concrete examples. Class worksheets provide ax² + bx + c cases with c ≠ 0.',
      warmup: 'Ask: "How does changing the planet affect the shape of the parabola?" Observe: Jupiter (high g) → narrow, steep arch; Pluto (low g) → wide, flat arch. Connect visually to the leading coefficient a.',
      teacherNotes: [
        'In the simulator, a = −g/(2vx²). Larger gravity → more negative a → narrower parabola.',
        'Switching to Jupiter (g = 24.79) makes a very negative; Pluto (g = 0.62) makes a nearly zero.',
        'For class problems with a > 1 and c ≠ 0: use the AC method or rectangle diagram.',
        'AC method: to factor ax² + bx + c, find two numbers multiplying to ac and adding to b.',
        'Rectangle diagram is powerful for visual learners; fill a 2×2 grid systematically.',
      ],
      discussion: [
        'How does a larger |a| affect the parabola\'s shape? (Narrower — steeper arch.)',
        'What value of a gives the widest possible parabola for a given speed? (Smallest |a| → lowest gravity → Pluto.)',
        'Can you find angle and speed settings on Earth that give a = exactly −0.02?',
      ],
      homework: 'Factor these quadratics using the AC method: (a) 2x² + 7x + 3, (b) 3x² − 5x − 2, (c) 6x² + x − 2. Show all steps including the rectangle diagram for one of them.',
    },
    activities: [
      {
        id: 'l4-planets',
        title: 'Gravity & Coefficient',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Switch planets to vary the leading coefficient a and observe how the parabola\'s shape changes.',
        prompts: [
          'On Earth (g = 9.81), note a in the general form. It is −g/(2vx²).',
          'Switch to Jupiter (g = 24.79). Watch a become much more negative — the arch is narrow.',
          'Switch to Pluto (g = 0.62). a is nearly zero — the flight is long and flat.',
          'The formula: a = −g/(2vx²). Larger gravity → more negative a → steeper, shorter arc.',
          'Launch on each planet. Compare landing distances for the same angle and speed.',
        ],
        overlays: { intercepts: true, vertex: true },
        equationForms: ['general', 'factored'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
      {
        id: 'l4-student',
        title: 'AC Method Practice',
        badge: null,
        type: 'student',
        desc: 'Practice the AC method with class worksheet problems alongside the simulation.',
        prompts: [
          'Factor 2x² + 7x + 3 using the AC method.',
          'Step 1: a·c = 2·3 = 6. Find two numbers multiplying to 6 and adding to 7: (1 and 6).',
          'Step 2: rewrite the middle term: 2x² + x + 6x + 3.',
          'Step 3: factor by grouping: x(2x + 1) + 3(2x + 1) = (x + 3)(2x + 1).',
          'Also try: 3x² − 5x − 2 and 6x² + x − 2. How does changing a affect the difficulty of factoring?',
        ],
        overlays: { intercepts: true },
        equationForms: ['general', 'factored'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
    ],
  },

  {
    id: 5,
    title: 'Zero Product Property',
    targets: [
      'Understand why setting a quadratic equal to 0 allows solving via the Zero Product Property.',
      'Solve quadratic equations written in factored form.',
      'Connect solving quadratics in factored form with x-intercepts on the graph.',
    ],
    plan: {
      overview: 'Students discover WHY factoring solves quadratics. Landing points are literally the zeros of the height function — a perfect physical demonstration of the Zero Product Property.',
      warmup: 'Show the factored form y = a·x·(x − R). Ask: "When does the minion touch the ground? What is y at that moment?" Guide to y = 0, then ask: "So what equation do we need to solve?"',
      teacherNotes: [
        'Zero Product Property: if A × B = 0, then A = 0 OR B = 0 (because only zero times anything equals zero).',
        'Applied: a·x·(x − R) = 0 → x = 0 or x − R = 0 → x = 0 or x = R.',
        'The x-intercepts ARE the solutions to y = 0.',
        'Key connection: "solving the equation" = "finding x-intercepts" = "finding where the minion lands."',
        'Use the Predict the Landing activity: students solve algebraically, then launch to verify.',
      ],
      discussion: [
        'Why does ZPP work? (A product equals zero only when at least one factor is zero.)',
        'What is special about x-intercepts? (They are where y = 0 — the minion\'s height is zero.)',
        'Could there be a parabola with only ONE x-intercept? With zero? Hint for Lesson 10!',
      ],
      homework: 'Before launching, record the factored form from the Equations panel. Solve for both x-intercepts using ZPP. Submit your predicted landing distance, then verify by launching with the basket at that position.',
    },
    activities: [
      {
        id: 'l5-demo',
        title: 'ZPP Demo',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Walk through setting y = 0 and applying the Zero Product Property to find the landing x-intercept.',
        prompts: [
          'The height equation is y = a·x·(x − R). The minion lands when y = 0.',
          'Set y = 0: a·x·(x − R) = 0.',
          'Zero Product Property: x = 0 OR (x − R) = 0.',
          'Solutions: x = 0 (launch point) and x = R (landing point).',
          'These are the x-intercepts shown on the chart. Launch to confirm they are correct!',
        ],
        overlays: { intercepts: true },
        equationForms: ['factored', 'general'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
      {
        id: 'l5-predict',
        title: 'Predict the Landing',
        badge: null,
        type: 'student',
        desc: 'Use ZPP and the factored equation to predict the landing distance — before you launch.',
        prompts: [
          'Read the factored form from the Equations panel. Write down a and R.',
          'Set y = 0 and write the equation: a·x·(x − R) = 0.',
          'Apply ZPP: x = 0 or x = R. The landing is at x = R.',
          'My predicted landing distance: x = ___ m.',
          'Set the basket to your prediction. Now launch! Did the minion land there?',
        ],
        overlays: { intercepts: false },
        equationForms: ['factored'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
    ],
  },

  {
    id: 6,
    title: 'Completing the Square',
    targets: [
      'Rewrite quadratic equations as perfect squares.',
      'Solve quadratic equations by completing the square.',
    ],
    plan: {
      overview: 'Students convert from general to vertex form by completing the square. The peak of the flight is the geometric meaning: completing the square algebraically reveals the exact physical coordinates of the highest point.',
      warmup: 'Show general form y = ax² + bx and vertex form y = a(x − h)² + k side by side. Ask: "How do you get from one to the other? What do h and k represent in the flight?" (Vertex = peak of arc.)',
      teacherNotes: [
        'Step 1: factor out a: y = a(x² + (b/a)x).',
        'Step 2: compute (b/(2a))² and add/subtract inside: y = a[(x + b/(2a))² − (b/(2a))²].',
        'Step 3: distribute a: y = a(x + b/(2a))² − b²/(4a).',
        'Result: h = −b/(2a), k = −b²/(4a). The vertex marker on the chart shows exactly this point!',
        'The "completing the square" method finds the peak of the flight path algebraically.',
      ],
      discussion: [
        'What does "completing the square" mean geometrically? (Rewriting to reveal the vertex — the peak.)',
        'If you know vertex form, how do you get back to general form? (Expand the squared term.)',
        'What information does each form highlight most clearly?',
      ],
      homework: 'Given y = −0.012x² + 0.84x, complete the square to convert to vertex form. Identify the vertex. Then find the simulation angle and speed that produce this equation and verify.',
    },
    activities: [
      {
        id: 'l6-steps',
        title: 'CTS Steps',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Walk through completing the square step-by-step. The vertex marker shows the geometric result.',
        prompts: [
          'Start: y = ax² + bx. Factor out a: y = a(x² + (b/a)x).',
          'Half the x-coefficient: b/(2a). Square it: (b/(2a))².',
          'Add and subtract inside brackets: y = a[(x + b/(2a))² − (b/(2a))²].',
          'Distribute a: y = a(x + b/(2a))² − b²/(4a).',
          'Vertex: h = −b/(2a), k = −b²/(4a). Enable the vertex overlay — does the chart match?',
        ],
        overlays: { vertex: true, axisSym: true },
        equationForms: ['general', 'vertex'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
      {
        id: 'l6-challenge',
        title: 'Vertex Challenge',
        badge: null,
        type: 'student',
        desc: 'Complete the square by hand to find the vertex, then verify by comparing to the chart.',
        prompts: [
          'Read a and b from the general form in the Equations panel.',
          'Calculate h = −b/(2a). This is the x-coordinate of the peak (axis of symmetry).',
          'Calculate k = −b²/(4a). This is the maximum height the minion reaches.',
          'Write vertex form: y = a(x − h)² + k.',
          'Launch and watch: does the minion reach height k at x-position h? Use the chart to check.',
        ],
        overlays: { vertex: false, axisSym: false },
        equationForms: ['general', 'vertex'],
        showTargetHeight: false,
        showDiscriminant: false,
      },
    ],
  },

  {
    id: 7,
    title: 'Circles & CTS',
    targets: [
      'Given an expanded equation of a circle, rewrite it to find the center and radius.',
    ],
    plan: {
      overview: 'Students apply completing the square to both x and y terms in circle equations. The same algebraic technique from Lesson 6 extends naturally — and the Circle Explorer shows the geometric result immediately.',
      warmup: 'Ask: "How is the equation of a circle similar to a quadratic? How is it different?" (Both involve x² terms; a circle also has y²; a circle is not a function.) Sketch (x − 3)² + (y + 2)² = 25 vs. x² + y² − 6x + 4y = 12.',
      teacherNotes: [
        'Standard form: (x − h)² + (y − k)² = r². Center = (h, k), radius = r.',
        'Expanded: x² + y² − 2hx − 2ky + (h² + k² − r²) = 0. Coefficients: D = −2h, E = −2k, F = h² + k² − r².',
        'To reverse: group x-terms and y-terms separately, complete the square in each, add the same amounts to the right side.',
        'Circle Explorer lets students adjust h, k, r and see both forms update live.',
        'Key difference from Lesson 6: you must add the completing-the-square amount to BOTH sides of the equation.',
      ],
      discussion: [
        'Why do you add to both sides of the equation? (To maintain equality.)',
        'What happens if −F + (D/2)² + (E/2)² = 0? (A "circle" of radius 0 — a single point.) What if < 0? (No real circle.)',
        'How is completing the square for a circle different from completing it for a parabola?',
      ],
      homework: 'Rewrite in standard form. Find center and radius. (a) x² + y² + 4x − 6y = 3, (b) x² + y² − 10x + 2y + 1 = 0, (c) 2x² + 2y² + 12x − 8y − 24 = 0.',
    },
    activities: [
      {
        id: 'l7-demo',
        title: 'Circle Explorer',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Adjust center h, k and radius r. Watch both standard and expanded forms update in real time.',
        prompts: [
          'Use the circle sliders to set center (h, k) and radius r.',
          'Standard form: (x − h)² + (y − k)² = r². Center and radius are explicit.',
          'Expanded form: x² + y² + Dx + Ey + F = 0, where D = −2h, E = −2k.',
          'Given the expanded form: h = −D/2, k = −E/2, r = √(h² + k² − F).',
          'Try: set D = −4, E = 6, F = −3. Work out h, k, r algebraically, then match with sliders to verify.',
        ],
        isCircleMode: true,
        overlays: {},
        equationForms: [],
        showTargetHeight: false,
        showDiscriminant: false,
      },
      {
        id: 'l7-solve',
        title: 'CTS for Circles',
        badge: null,
        type: 'student',
        desc: 'Complete the square in both x and y to find center and radius from expanded form.',
        prompts: [
          'Start with: x² + y² + Dx + Ey + F = 0.',
          'Group: (x² + Dx) + (y² + Ey) = −F.',
          'Complete for x: add (D/2)² to both sides.',
          'Complete for y: add (E/2)² to both sides.',
          'Result: (x + D/2)² + (y + E/2)² = −F + (D/2)² + (E/2)².',
          'Center = (−D/2, −E/2); radius = √(right side). Verify with the circle explorer!',
        ],
        isCircleMode: true,
        overlays: {},
        equationForms: [],
        showTargetHeight: false,
        showDiscriminant: false,
      },
    ],
  },

  {
    id: 8,
    title: 'Quadratic Formula',
    targets: [
      'Solve quadratic equations with real solutions using the quadratic formula.',
    ],
    plan: {
      overview: 'Students apply the quadratic formula to find where the minion reaches a specific height. The target height slider makes the problem physical and immediately verifiable by launching.',
      warmup: 'Ask: "What if the quadratic doesn\'t factor easily? We need a method that always works." Introduce x = (−b ± √(b² − 4ac)) / (2a) and note it was derived by completing the square (Lesson 6).',
      teacherNotes: [
        'For landing (c = 0): formula gives x = (−b ± |b|)/(2a) = 0 and −b/a = R. Simple case!',
        'For y = T: solve ax² + bx − T = 0. Apply formula with c → −T.',
        'Result: x = (−b ± √(b² + 4aT))/(2a). Note: a is negative, so b² + 4aT can be negative if T > max height.',
        'The two solutions are x-values where the minion is at height T (one ascending, one descending).',
        'Use the target height slider: students compute, then launch to see the minion cross at predicted x-values.',
      ],
      discussion: [
        'The ± gives two solutions. What do they mean physically? (Ascending and descending crossings.)',
        'How is the quadratic formula derived? (By completing the square — Lesson 6 connection!)',
        'When is factoring preferable? When is the formula preferable?',
      ],
      homework: 'Set angle = 55°, speed = 50 m/s, Earth. Set target height = 15 m. Use the quadratic formula to find both x-values where the minion is at 15 m height. Launch to verify.',
    },
    activities: [
      {
        id: 'l8-demo',
        title: 'Formula Demo',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Use the target height slider to pose the problem y = T, then solve with the quadratic formula.',
        prompts: [
          'Set a target height T with the slider. A horizontal line appears on the chart.',
          'We need to solve ax² + bx = T, or equivalently ax² + bx − T = 0.',
          'Quadratic formula: x = (−b ± √(b² − 4ac))/(2a) where c = −T here.',
          'Simplify: x = (−b ± √(b² + 4aT))/(2a). Calculate both solutions.',
          'Launch! The minion should cross the target line at your two predicted x-values.',
        ],
        overlays: { vertex: true, axisSym: true, intercepts: true, targetHeight: true, solutionPoints: true },
        equationForms: ['general', 'vertex'],
        showTargetHeight: true,
        showDiscriminant: false,
      },
      {
        id: 'l8-predict',
        title: 'Formula Challenge',
        badge: null,
        type: 'student',
        desc: 'Set a target height, apply the quadratic formula, predict two x-values, then launch to verify.',
        prompts: [
          'Set target height T using the slider. Write down a, b, and T.',
          'Set up: solve ax² + bx − T = 0. Identify c = −T for the formula.',
          'Apply: x = (−b ± √(b² − 4ac))/(2a). Calculate both solutions.',
          'Record: x₁ = ___ m (ascending), x₂ = ___ m (descending).',
          'Launch! Does the minion cross the target line at those two x-values?',
        ],
        overlays: { targetHeight: true, solutionPoints: false },
        equationForms: ['general'],
        showTargetHeight: true,
        showDiscriminant: false,
      },
    ],
  },

  {
    id: 9,
    title: 'Imaginary Numbers',
    targets: [
      'Understand what the imaginary number i is, why it is needed, and how to simplify expressions using it.',
      'Simplify square roots of negative numbers using i.',
      'Solve quadratic equations with imaginary solutions and identify conjugate pairs.',
    ],
    plan: {
      overview: 'Students discover imaginary numbers through a concrete failure: raise the target height above the max height and the quadratic formula requires √(negative). The parabola never reaches that line — and the algebra explains why.',
      warmup: 'Raise the target height above the flight maximum. Ask: "How many times does the minion reach this height?" (Never.) "What does the algebra give us when we try to solve?" Run the formula — discriminant is negative.',
      teacherNotes: [
        'Discriminant D = b² + 4aT. When T > max height (vertex k), D < 0.',
        'Real numbers have no √(negative). This is why we extend to imaginary numbers.',
        'Define: i = √(−1). Then √(−n) = i√n for n > 0. Example: √(−9) = 3i.',
        'Solutions: x = (−b ± i√|D|)/(2a). These are conjugate pairs: m + ni and m − ni.',
        'Note: the real part m = −b/(2a) = h, the axis of symmetry! Complex solutions still have the axis as their midpoint.',
      ],
      discussion: [
        'Why can\'t we take √(negative) in real numbers? (No real number squares to give a negative.)',
        'What does an imaginary solution mean graphically? (The parabola doesn\'t cross that line.)',
        'Conjugate pairs: a + bi and a − bi always appear together for real-coefficient quadratics. Why?',
      ],
      homework: 'Compute the discriminant and classify solutions: (a) x² + 4 = 0, (b) x² + 2x + 5 = 0, (c) x² − 6x + 9 = 0. For the imaginary ones, write the solutions using i and identify the conjugate pair.',
    },
    activities: [
      {
        id: 'l9-explorer',
        title: 'Imaginary Explorer',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Slide the target height through the vertex to show the exact moment D goes from positive to negative.',
        prompts: [
          'Target below the flight peak: D = b² + 4aT > 0 — two real solutions (two crossings).',
          'Target exactly at the vertex (max height): D = 0 — one solution (tangent at the peak).',
          'Target above the peak: D < 0 — the parabola never reaches this height.',
          'Now D is negative: x = (−b ± √D)/(2a) = (−b ± i√|D|)/(2a).',
          'These are conjugate pair: m ± ni where m = −b/(2a) (the axis of symmetry!).',
        ],
        overlays: { vertex: true, axisSym: true, targetHeight: true, discriminant: true, solutionPoints: true },
        equationForms: ['general', 'vertex'],
        showTargetHeight: true,
        showDiscriminant: true,
      },
      {
        id: 'l9-simplify',
        title: 'Simplify with i',
        badge: null,
        type: 'student',
        desc: 'Raise the target above the max height and compute the imaginary solutions step by step.',
        prompts: [
          'Set the target height ABOVE the flight maximum. The parabola never crosses this line.',
          'Read a, b, T. Compute D = b² + 4aT. It should be negative!',
          'Write D = −|D|. Then √D = √(−|D|) = i√|D|.',
          'Solutions: x = (−b ± i√|D|)/(2a).',
          'Identify real part m = −b/(2a) and imaginary part n = √|D|/(2|a|). Solutions: m + ni and m − ni.',
        ],
        overlays: { targetHeight: true, discriminant: true },
        equationForms: ['general'],
        showTargetHeight: true,
        showDiscriminant: true,
      },
    ],
  },

  {
    id: 10,
    title: 'Discriminant',
    targets: [
      'Solve quadratic equations with nonreal solutions using the quadratic formula.',
      'Use the discriminant to determine the type and number of solutions.',
      'Use the graph of a quadratic to determine the number and type of solutions.',
    ],
    plan: {
      overview: 'Students master the discriminant as a predictive tool. Evaluate D = b² − 4ac first to classify solutions without fully solving. The target height slider creates a live visual demonstration of all three discriminant cases.',
      warmup: 'Present three target heights: below vertex (2 crossings), at vertex (1 crossing), above vertex (0 crossings). Ask: "Without solving, how many solutions does each have? How can you tell from the graph alone?"',
      teacherNotes: [
        'For y = T: D_T = b² − 4a(−T) = b² + 4aT.',
        'D > 0: two distinct real solutions — parabola crosses target line twice.',
        'D = 0: one repeated real solution — parabola is tangent to the line at vertex.',
        'D < 0: two complex conjugate solutions — parabola never reaches the line.',
        'Students should be able to determine solution type from a graph by counting intersections.',
      ],
      discussion: [
        'Can you determine the sign of D just by looking at the graph? (Yes — count crossings.)',
        'What specific target height gives D = 0? (The vertex height k — the maximum.)',
        'Given only the discriminant value, what can you say? (Solution type.) What can\'t you say? (Exact solutions.)',
      ],
      homework: 'Compute D and classify: (a) 2x² − 3x + 1 = 0, (b) x² + 6x + 9 = 0, (c) x² + x + 1 = 0. Then solve each and verify your classification. For each, describe what the graph looks like relative to the x-axis.',
    },
    activities: [
      {
        id: 'l10-dashboard',
        title: 'Discriminant Dashboard',
        badge: 'DEMO',
        type: 'teacher-demo',
        desc: 'Live discriminant display as the target height varies — watch D transition from positive to zero to negative.',
        prompts: [
          'Target below the vertex: D = b² + 4aT > 0. Two real solution x-values appear on the chart.',
          'Raise the target to the vertex height k: D → 0. One solution — the tangent point.',
          'Raise above the vertex: D < 0. No real solutions — no crossing points shown.',
          'Formula: x = (−b ± √D)/(2a). When D < 0, solutions become complex.',
          'The discriminant PREDICTS the solution type before you even solve the equation!',
        ],
        overlays: { vertex: true, axisSym: true, targetHeight: true, discriminant: true, solutionPoints: true },
        equationForms: ['general', 'vertex'],
        showTargetHeight: true,
        showDiscriminant: true,
      },
      {
        id: 'l10-predict',
        title: 'Predict & Verify',
        badge: null,
        type: 'student',
        desc: 'Evaluate D for a chosen target height, classify the solutions, then solve and launch to verify.',
        prompts: [
          'Set a target height T. Write down a, b, and T.',
          'Compute D = b² + 4aT. Is it positive, zero, or negative?',
          'Classify: D > 0 → two real solutions; D = 0 → one solution; D < 0 → imaginary.',
          'If D > 0: apply the quadratic formula to find x₁ and x₂. Record them.',
          'Launch and verify: does the minion cross the target line at your x₁ and x₂?',
        ],
        overlays: { targetHeight: true, discriminant: true },
        equationForms: ['general'],
        showTargetHeight: true,
        showDiscriminant: true,
      },
      {
        id: 'l10-graph',
        title: 'Graph → Solutions',
        badge: null,
        type: 'student',
        desc: 'Read the chart to determine solution type from the graph, then verify algebraically.',
        prompts: [
          'Set a target height and look at the chart. Count intersections of the trajectory and the line.',
          '2 intersections → D > 0 (two real solutions).',
          '1 touching point → D = 0 (one repeated solution).',
          '0 intersections → D < 0 (imaginary solutions).',
          'Compute D algebraically to confirm your graphical prediction.',
          'If D > 0: solve with the formula. Do the x-values match the chart intersection points?',
        ],
        overlays: { vertex: true, axisSym: true, targetHeight: true, discriminant: true, solutionPoints: true },
        equationForms: ['general', 'vertex'],
        showTargetHeight: true,
        showDiscriminant: true,
      },
    ],
  },
];

const FREE_PLAY = {
  id: 0,
  title: 'Free Play',
  activities: [
    {
      id: 'free',
      title: 'Free Play',
      badge: null,
      type: 'free',
      desc: 'Launch minions across planets — no lesson, just exploration!',
      prompts: [],
      overlays: {},
      equationForms: ['general'],
      showTargetHeight: false,
      showDiscriminant: false,
    },
  ],
};
